version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./tasks.sql:/tasks.sql
      - ./init-db.sh:/init-db.sh
